// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: protos/cluster.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropagateWriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MappingsIPNS string `protobuf:"bytes,1,opt,name=MappingsIPNS,proto3" json:"MappingsIPNS,omitempty"`
}

func (x *PropagateWriteRequest) Reset() {
	*x = PropagateWriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cluster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropagateWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropagateWriteRequest) ProtoMessage() {}

func (x *PropagateWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropagateWriteRequest.ProtoReflect.Descriptor instead.
func (*PropagateWriteRequest) Descriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *PropagateWriteRequest) GetMappingsIPNS() string {
	if x != nil {
		return x.MappingsIPNS
	}
	return ""
}

type PropagateWriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PropagateWriteResponse) Reset() {
	*x = PropagateWriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cluster_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropagateWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropagateWriteResponse) ProtoMessage() {}

func (x *PropagateWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropagateWriteResponse.ProtoReflect.Descriptor instead.
func (*PropagateWriteResponse) Descriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{1}
}

type SyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cluster_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found        bool   `protobuf:"varint,1,opt,name=Found,proto3" json:"Found,omitempty"`
	CID          string `protobuf:"bytes,2,opt,name=CID,proto3" json:"CID,omitempty"`
	MappingsIPNS string `protobuf:"bytes,3,opt,name=MappingsIPNS,proto3" json:"MappingsIPNS,omitempty"`
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cluster_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *SyncResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *SyncResponse) GetCID() string {
	if x != nil {
		return x.CID
	}
	return ""
}

func (x *SyncResponse) GetMappingsIPNS() string {
	if x != nil {
		return x.MappingsIPNS
	}
	return ""
}

type GetNodetxtIPNSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetNodetxtIPNSRequest) Reset() {
	*x = GetNodetxtIPNSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cluster_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodetxtIPNSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodetxtIPNSRequest) ProtoMessage() {}

func (x *GetNodetxtIPNSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodetxtIPNSRequest.ProtoReflect.Descriptor instead.
func (*GetNodetxtIPNSRequest) Descriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{4}
}

type GetNodetxtIPNSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodetxtIPNS string `protobuf:"bytes,1,opt,name=NodetxtIPNS,proto3" json:"NodetxtIPNS,omitempty"`
}

func (x *GetNodetxtIPNSResponse) Reset() {
	*x = GetNodetxtIPNSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cluster_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodetxtIPNSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodetxtIPNSResponse) ProtoMessage() {}

func (x *GetNodetxtIPNSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodetxtIPNSResponse.ProtoReflect.Descriptor instead.
func (*GetNodetxtIPNSResponse) Descriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *GetNodetxtIPNSResponse) GetNodetxtIPNS() string {
	if x != nil {
		return x.NodetxtIPNS
	}
	return ""
}

var File_protos_cluster_proto protoreflect.FileDescriptor

var file_protos_cluster_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x3b,
	0x0a, 0x15, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x61, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x73, 0x49, 0x50, 0x4e, 0x53, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x50, 0x4e, 0x53, 0x22, 0x18, 0x0a, 0x16, 0x50,
	0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x5a, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x43, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43, 0x49, 0x44, 0x12, 0x22,
	0x0a, 0x0c, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x50, 0x4e, 0x53, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x50,
	0x4e, 0x53, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x74, 0x78, 0x74,
	0x49, 0x50, 0x4e, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x74, 0x78, 0x74, 0x49, 0x50, 0x4e, 0x53, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x74, 0x78, 0x74,
	0x49, 0x50, 0x4e, 0x53, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4e, 0x6f, 0x64, 0x65,
	0x74, 0x78, 0x74, 0x49, 0x50, 0x4e, 0x53, 0x32, 0xee, 0x01, 0x0a, 0x17, 0x49, 0x6d, 0x6d, 0x75,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x4f, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72,
	0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x13, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x74, 0x78, 0x74, 0x49, 0x50, 0x4e, 0x53, 0x12, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x74, 0x78, 0x74, 0x49, 0x50, 0x4e,
	0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x74, 0x78, 0x74, 0x49, 0x50, 0x4e, 0x53,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_cluster_proto_rawDescOnce sync.Once
	file_protos_cluster_proto_rawDescData = file_protos_cluster_proto_rawDesc
)

func file_protos_cluster_proto_rawDescGZIP() []byte {
	file_protos_cluster_proto_rawDescOnce.Do(func() {
		file_protos_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_cluster_proto_rawDescData)
	})
	return file_protos_cluster_proto_rawDescData
}

var file_protos_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_cluster_proto_goTypes = []interface{}{
	(*PropagateWriteRequest)(nil),  // 0: server.PropagateWriteRequest
	(*PropagateWriteResponse)(nil), // 1: server.PropagateWriteResponse
	(*SyncRequest)(nil),            // 2: server.SyncRequest
	(*SyncResponse)(nil),           // 3: server.SyncResponse
	(*GetNodetxtIPNSRequest)(nil),  // 4: server.GetNodetxtIPNSRequest
	(*GetNodetxtIPNSResponse)(nil), // 5: server.GetNodetxtIPNSResponse
}
var file_protos_cluster_proto_depIdxs = []int32{
	0, // 0: server.ImmutableStorageCluster.PropagateWrite:input_type -> server.PropagateWriteRequest
	2, // 1: server.ImmutableStorageCluster.Sync:input_type -> server.SyncRequest
	4, // 2: server.ImmutableStorageCluster.GetNodetxtIPNS:input_type -> server.GetNodetxtIPNSRequest
	1, // 3: server.ImmutableStorageCluster.PropagateWrite:output_type -> server.PropagateWriteResponse
	3, // 4: server.ImmutableStorageCluster.Sync:output_type -> server.SyncResponse
	5, // 5: server.ImmutableStorageCluster.GetNodetxtIPNS:output_type -> server.GetNodetxtIPNSResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_cluster_proto_init() }
func file_protos_cluster_proto_init() {
	if File_protos_cluster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_cluster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropagateWriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cluster_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropagateWriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cluster_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cluster_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cluster_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodetxtIPNSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cluster_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodetxtIPNSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_cluster_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_cluster_proto_goTypes,
		DependencyIndexes: file_protos_cluster_proto_depIdxs,
		MessageInfos:      file_protos_cluster_proto_msgTypes,
	}.Build()
	File_protos_cluster_proto = out.File
	file_protos_cluster_proto_rawDesc = nil
	file_protos_cluster_proto_goTypes = nil
	file_protos_cluster_proto_depIdxs = nil
}
