// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: protos/readwrite.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImmutableStorageClient is the client API for ImmutableStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImmutableStorageClient interface {
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	AvailableKeys(ctx context.Context, in *AvailableKeysRequest, opts ...grpc.CallOption) (*AvailableKeysResponse, error)
}

type immutableStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewImmutableStorageClient(cc grpc.ClientConnInterface) ImmutableStorageClient {
	return &immutableStorageClient{cc}
}

func (c *immutableStorageClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, "/server.ImmutableStorage/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immutableStorageClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/server.ImmutableStorage/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immutableStorageClient) AvailableKeys(ctx context.Context, in *AvailableKeysRequest, opts ...grpc.CallOption) (*AvailableKeysResponse, error) {
	out := new(AvailableKeysResponse)
	err := c.cc.Invoke(ctx, "/server.ImmutableStorage/AvailableKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImmutableStorageServer is the server API for ImmutableStorage service.
// All implementations must embed UnimplementedImmutableStorageServer
// for forward compatibility
type ImmutableStorageServer interface {
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	AvailableKeys(context.Context, *AvailableKeysRequest) (*AvailableKeysResponse, error)
	mustEmbedUnimplementedImmutableStorageServer()
}

// UnimplementedImmutableStorageServer must be embedded to have forward compatible implementations.
type UnimplementedImmutableStorageServer struct {
}

func (UnimplementedImmutableStorageServer) Store(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedImmutableStorageServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedImmutableStorageServer) AvailableKeys(context.Context, *AvailableKeysRequest) (*AvailableKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AvailableKeys not implemented")
}
func (UnimplementedImmutableStorageServer) mustEmbedUnimplementedImmutableStorageServer() {}

// UnsafeImmutableStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImmutableStorageServer will
// result in compilation errors.
type UnsafeImmutableStorageServer interface {
	mustEmbedUnimplementedImmutableStorageServer()
}

func RegisterImmutableStorageServer(s grpc.ServiceRegistrar, srv ImmutableStorageServer) {
	s.RegisterService(&ImmutableStorage_ServiceDesc, srv)
}

func _ImmutableStorage_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmutableStorageServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.ImmutableStorage/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmutableStorageServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmutableStorage_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmutableStorageServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.ImmutableStorage/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmutableStorageServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmutableStorage_AvailableKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailableKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmutableStorageServer).AvailableKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.ImmutableStorage/AvailableKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmutableStorageServer).AvailableKeys(ctx, req.(*AvailableKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImmutableStorage_ServiceDesc is the grpc.ServiceDesc for ImmutableStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImmutableStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.ImmutableStorage",
	HandlerType: (*ImmutableStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _ImmutableStorage_Store_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ImmutableStorage_Read_Handler,
		},
		{
			MethodName: "AvailableKeys",
			Handler:    _ImmutableStorage_AvailableKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/readwrite.proto",
}
